#!/bin/sh

DAEMON="tqftpserv"
TQFTPSERV="/usr/bin/tqftpserv"
PIDFILE="/var/run/$DAEMON.pid"

start() {
	printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon -S -q -b -m -p "$PIDFILE" -x $TQFTPSERV
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop && start
}

case "$1" in
	start|stop)
		"$1";;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
